In [1]:
## IMPORTING THE DATA
import pandas as pd
import numpy as np
df = pd.read_csv("all_matches.csv",low_memory = False)

In [2]:
## PERFORMING EDA AND DATA CLEANING
df = df[df.ball <= 6.0]
df = df[df.innings < 3]

In [3]:
df = df.fillna(0)

In [4]:
df['total_runs'] = df.runs_off_bat + df.extras

from datetime import datetime
df['start_date'] = df['start_date'].apply(lambda x: datetime.strptime(x, '%Y-%m-%d'))

In [5]:
df.drop(['runs_off_bat','season','extras','wides','noballs','byes','legbyes','penalty','other_player_dismissed','other_wicket_type','non_striker','match_id','player_dismissed','wicket_type'],axis = 1,inplace = True)

In [6]:
dfcopy = df
dfcopy.columns

Index(['start_date', 'venue', 'innings', 'ball', 'batting_team',
       'bowling_team', 'striker', 'bowler', 'total_runs'],
      dtype='object')

In [7]:
dfcopy['target'] = 0
dfcopy

,start_date,venue,innings,ball,batting_team,bowling_team,striker,bowler,total_runs,target
0,2008-04-18,M Chinnaswamy Stadium,1,0.1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,1,0
1,2008-04-18,M Chinnaswamy Stadium,1,0.2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,0,0
2,2008-04-18,M Chinnaswamy Stadium,1,0.3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,1,0
3,2008-04-18,M Chinnaswamy Stadium,1,0.4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,0,0
4,2008-04-18,M Chinnaswamy Stadium,1,0.5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,0,0
...,...,...,...,...,...,...,...,...,...,...
198883,2021-04-27,"Narendra Modi Stadium, Ahmedabad",2,5.2,Delhi Capitals,Royal Challengers Bangalore,RR Pant,DR Sams,0,0
198884,2021-04-27,"Narendra Modi Stadium, Ahmedabad",2,5.3,Delhi Capitals,Royal Challengers Bangalore,RR Pant,DR Sams,4,0
198885,2021-04-27,"Narendra Modi Stadium, Ahmedabad",2,5.4,Delhi Capitals,Royal Challengers Bangalore,RR Pant,DR Sams,0,0
198886,2021-04-27,"Narendra Modi Stadium, Ahmedabad",2,5.5,Delhi Capitals,Royal Challengers Bangalore,RR Pant,DR Sams,2,0
198887,2021-04-27,"Narendra Modi Stadium, Ahmedabad",2,5.6,Delhi Capitals,Royal Challengers Bangalore,RR Pant,DR Sams,1,0

In [8]:
dfcopy.loc[0, 'target'] = dfcopy.loc[0, 'total_runs']

dff = dfcopy
dff = dff.reset_index()
for i in range(1, len(dff)):
    if dff.loc[i,'ball'] == 0.1:
        dff.loc[i,'target'] = 0
        continue
    dff.loc[i, 'target'] = dff.loc[i-1, 'target'] + dff.loc[i, 'total_runs']

dff

,index,start_date,venue,innings,ball,batting_team,bowling_team,striker,bowler,total_runs,target
0,0,2008-04-18,M Chinnaswamy Stadium,1,0.1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,1,1
1,1,2008-04-18,M Chinnaswamy Stadium,1,0.2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,0,1
2,2,2008-04-18,M Chinnaswamy Stadium,1,0.3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,1,2
3,3,2008-04-18,M Chinnaswamy Stadium,1,0.4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,0,2
4,4,2008-04-18,M Chinnaswamy Stadium,1,0.5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,0,2
...,...,...,...,...,...,...,...,...,...,...,...
62566,198883,2021-04-27,"Narendra Modi Stadium, Ahmedabad",2,5.2,Delhi Capitals,Royal Challengers Bangalore,RR Pant,DR Sams,0,36
62567,198884,2021-04-27,"Narendra Modi Stadium, Ahmedabad",2,5.3,Delhi Capitals,Royal Challengers Bangalore,RR Pant,DR Sams,4,40
62568,198885,2021-04-27,"Narendra Modi Stadium, Ahmedabad",2,5.4,Delhi Capitals,Royal Challengers Bangalore,RR Pant,DR Sams,0,40
62569,198886,2021-04-27,"Narendra Modi Stadium, Ahmedabad",2,5.5,Delhi Capitals,Royal Challengers Bangalore,RR Pant,DR Sams,2,42
62570,198887,2021-04-27,"Narendra Modi Stadium, Ahmedabad",2,5.6,Delhi Capitals,Royal Challengers Bangalore,RR Pant,DR Sams,1,43

In [9]:
dfcopy = dff
dfcopy = dfcopy.reset_index()
dfcopy = dfcopy.drop(columns = ['total_runs','index','level_0'])
dfcopy

,start_date,venue,innings,ball,batting_team,bowling_team,striker,bowler,target
0,2008-04-18,M Chinnaswamy Stadium,1,0.1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,1
1,2008-04-18,M Chinnaswamy Stadium,1,0.2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,1
2,2008-04-18,M Chinnaswamy Stadium,1,0.3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2
3,2008-04-18,M Chinnaswamy Stadium,1,0.4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2
4,2008-04-18,M Chinnaswamy Stadium,1,0.5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2
...,...,...,...,...,...,...,...,...,...
62566,2021-04-27,"Narendra Modi Stadium, Ahmedabad",2,5.2,Delhi Capitals,Royal Challengers Bangalore,RR Pant,DR Sams,36
62567,2021-04-27,"Narendra Modi Stadium, Ahmedabad",2,5.3,Delhi Capitals,Royal Challengers Bangalore,RR Pant,DR Sams,40
62568,2021-04-27,"Narendra Modi Stadium, Ahmedabad",2,5.4,Delhi Capitals,Royal Challengers Bangalore,RR Pant,DR Sams,40
62569,2021-04-27,"Narendra Modi Stadium, Ahmedabad",2,5.5,Delhi Capitals,Royal Challengers Bangalore,RR Pant,DR Sams,42
62570,2021-04-27,"Narendra Modi Stadium, Ahmedabad",2,5.6,Delhi Capitals,Royal Challengers Bangalore,RR Pant,DR Sams,43

In [10]:
dfcopy['batting_team'] = dfcopy['batting_team'].replace(['Kings XI Punjab'],'Punjab Kings')
dfcopy['batting_team'] = dfcopy['batting_team'].replace(['Delhi Daredevils'],'Delhi Capitals')
dfcopy['bowling_team'] = dfcopy['bowling_team'].replace(['Kings XI Punjab'],'Punjab Kings')
dfcopy['bowling_team'] = dfcopy['bowling_team'].replace(['Delhi Daredevils'],'Punjab Kings')
dfcopy['venue'] = dfcopy['venue'].replace(['M.Chinnaswamy Stadium'],'M Chinnaswamy Stadium')
dfcopy['venue'] = dfcopy['venue'].replace(['Wankhede Stadium, Mumbai'],'Wankhede Stadium' )
dfcopy['venue'] = dfcopy['venue'].replace(['MA Chidambaram Stadium, Chepauk','MA Chidambaram Stadium, Chepauk, Chennai'],'MA Chidambaram Stadium' )
dfcopy['venue'] = dfcopy['venue'].replace(['Punjab Cricket Association IS Bindra Stadium, Mohali','Punjab Cricket Association Stadium, Mohali'],'Punjab Cricket Association IS Bindra Stadium' )
dfcopy['venue'] = dfcopy['venue'].replace(['Rajiv Gandhi International Stadium, Uppal'],'Rajiv Gandhi International Stadium' )

In [11]:
current_teams = ['Royal Challengers Bangalore', 'Kolkata Knight Riders' ,'Punjab Kings',
 'Chennai Super Kings', 'Rajasthan Royals', 'Mumbai Indians', 'Sunrisers Hyderabad', 'Delhi Capitals']
dfcopy = dfcopy[(dfcopy['batting_team'].isin(current_teams)) & (dfcopy['bowling_team'].isin(current_teams))]

In [12]:
dfcopy = dfcopy.reset_index()
dfcopy = dfcopy.drop(columns = ['index'])
dfcopy

,start_date,venue,innings,ball,batting_team,bowling_team,striker,bowler,target
0,2008-04-18,M Chinnaswamy Stadium,1,0.1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,1
1,2008-04-18,M Chinnaswamy Stadium,1,0.2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,1
2,2008-04-18,M Chinnaswamy Stadium,1,0.3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2
3,2008-04-18,M Chinnaswamy Stadium,1,0.4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2
4,2008-04-18,M Chinnaswamy Stadium,1,0.5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2
...,...,...,...,...,...,...,...,...,...
48738,2021-04-27,"Narendra Modi Stadium, Ahmedabad",2,5.2,Delhi Capitals,Royal Challengers Bangalore,RR Pant,DR Sams,36
48739,2021-04-27,"Narendra Modi Stadium, Ahmedabad",2,5.3,Delhi Capitals,Royal Challengers Bangalore,RR Pant,DR Sams,40
48740,2021-04-27,"Narendra Modi Stadium, Ahmedabad",2,5.4,Delhi Capitals,Royal Challengers Bangalore,RR Pant,DR Sams,40
48741,2021-04-27,"Narendra Modi Stadium, Ahmedabad",2,5.5,Delhi Capitals,Royal Challengers Bangalore,RR Pant,DR Sams,42
48742,2021-04-27,"Narendra Modi Stadium, Ahmedabad",2,5.6,Delhi Capitals,Royal Challengers Bangalore,RR Pant,DR Sams,43

In [13]:
current_venues = ['M Chinnaswamy Stadium','Eden Gardens', 'Feroz Shah Kotla', 'MA Chidambaram Stadium','Wankhede Stadium']

for i in range(0, len(dfcopy)):
      if dfcopy.loc[i,'venue'] not in current_venues:
             dfcopy.loc[i,'venue'] = 'Others'

In [14]:
#ONE HOT ENCODING
from sklearn.preprocessing import LabelEncoder
import joblib

venue_encoder = LabelEncoder()
team_encoder = LabelEncoder()
striker_encoder = LabelEncoder()
bowler_encoder = LabelEncoder()
cols = ['venue','batting_team','bowling_team','striker','bowler']

dfcopy['venue'] = venue_encoder.fit_transform(dfcopy['venue'])
dfcopy['batting_team'] = team_encoder.fit_transform(dfcopy['batting_team'])
dfcopy['bowling_team'] = team_encoder.fit_transform(dfcopy['bowling_team'])
dfcopy['striker'] = striker_encoder.fit_transform(dfcopy['striker'])
dfcopy['bowler'] = bowler_encoder.fit_transform(dfcopy['bowler'])
joblib.dump(venue_encoder, 'venue_encoder.joblib')
joblib.dump(team_encoder, 'team_encoder.joblib')
joblib.dump(striker_encoder, 'striker_encoder.joblib')
joblib.dump(bowler_encoder, 'bowler_encoder.joblib')

dfcopy

,start_date,venue,innings,ball,batting_team,bowling_team,striker,bowler,target
0,2008-04-18,2,1,0.1,2,6,210,207,1
1,2008-04-18,2,1,0.2,2,6,34,207,1
2,2008-04-18,2,1,0.3,2,6,34,207,2
3,2008-04-18,2,1,0.4,2,6,34,207,2
4,2008-04-18,2,1,0.5,2,6,34,207,2
...,...,...,...,...,...,...,...,...,...
48738,2021-04-27,4,2,5.2,1,6,192,83,36
48739,2021-04-27,4,2,5.3,1,6,192,83,40
48740,2021-04-27,4,2,5.4,1,6,192,83,40
48741,2021-04-27,4,2,5.5,1,6,192,83,42
48742,2021-04-27,4,2,5.6,1,6,192,83,43

In [15]:
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt

In [16]:
final_df = dfcopy

In [17]:
final_df.drop(labels='start_date', axis=True, inplace=True)

In [18]:
#Splitting the data into train and test set
X = final_df.drop(labels='target', axis=1)
y = final_df['target'].values
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25,random_state = 42)

In [19]:
#USING RANDOM FOREST CLASSIFIER
from sklearn.ensemble import RandomForestRegressor
forest = RandomForestRegressor()
# Train Model
forest.fit(X_train, y_train)

RandomForestRegressor()

In [20]:
# Evaluate Model
train_score_forest = str(forest.score(X_train, y_train)*100)
test_score_forest = str(forest.score(X_test, y_test)*100)
print(f'Train Score : {train_score_forest[:5]}%\nTest Score : {test_score_forest[:5]}%')

Train Score : 97.23%
Test Score : 81.60%

In [21]:
from sklearn.metrics import mean_absolute_error as mae, mean_squared_error as mse
print("---- Random Forest Regression - Model Evaluation ----")
print("Mean Absolute Error (MAE): {}".format(mae(y_test, forest.predict(X_test))))
print("Mean Squared Error (MSE): {}".format(mse(y_test, forest.predict(X_test))))
print("Root Mean Squared Error (RMSE): {}".format(np.sqrt(mse(y_test, forest.predict(X_test)))))

---- Random Forest Regression - Model Evaluation ----
Mean Absolute Error (MAE): 4.933652939621059
Mean Squared Error (MSE): 45.96125251953302
Root Mean Squared Error (RMSE): 6.7794728791796945

In [22]:
joblib.dump(forest, 'rf_encoder.joblib')

['rf_encoder.joblib']